Repository neverm1ndo/lars, pull requests merged in 2024-02, with the labels that each got.

#35 i18n(admins) add localization tokens
  src/app/app.module.ts
  src/app/home/admins/admins.component.html
  src/app/home/admins/admins.component.scss
  src/app/home/admins/admins.component.ts
  src/assets/i18n/admins/ru.json
  src/assets/i18n/app/ru.json
Labels: localization

#36 i18n(config, banhammer, dashboard) add localization tokens
  .eslintrc.json
  .prettierignore
  src/app/app.module.ts
  src/app/bans/bans-routing.module.ts
  src/app/bans/bans.module.ts
  src/app/bans/containers/banhammer/banhammer.component.html
  src/app/bans/containers/banhammer/banhammer.component.scss
  src/app/bans/containers/banhammer/banhammer.component.spec.ts
  src/app/bans/containers/banhammer/banhammer.component.ts
  src/app/configs/binary-doc/binary-doc.component.html
  src/app/configs/config-editor/config-editor.component.html
  src/app/configs/empty-doc/empty-doc.component.html
  src/app/configs/text-editor/text-editor.component.html
  src/app/home/dashboard/dashboard.component.html
  src/app/home/home-routing.module.ts
  src/app/home/home.module.ts
  src/app/shared/components/line-process/log-processes.ts
  src/assets/i18n/app/ru.json
  src/assets/i18n/bans/ru.json
  src/assets/i18n/configs/ru.json
  src/assets/i18n/dashboard/ru.json
Labels: localization

#39 fix(configs/search): fix search matches counter
  src/app/configs/text-editor/text-editor.component.ts
Labels: bug

#40 feature(serverlog-monitor): add server log monitor feature
  main.ts
  package.json
  src/app/api/interceptors/jwt.interceptor.ts
  src/app/app-routing.module.ts
  src/app/app.component.html
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/app.server.module.ts
  src/app/dev-server-controls/dev-server-controls.component.html
  src/app/dev-server-controls/dev-server-controls.component.ts
  src/app/guards/auth.guard.ts
  src/app/guards/login.guard.ts
  src/app/guards/not-changed-document.guard.ts
  src/app/home/dashboard/dashboard.component.ts
  src/app/home/home-routing.module.ts
  src/app/home/home.component.ts
  src/app/home/home.module.ts
  src/app/login/login-routing.module.ts
  src/app/login/login.module.ts
  src/app/notifications/notifications.service.ts
  src/app/server-stat-graph/server-stat-graph.component.ts
  src/app/serverlog-monitor/serverlog-monitor-routing.module.ts
  src/app/serverlog-monitor/serverlog-monitor.component.html
  src/app/serverlog-monitor/serverlog-monitor.component.scss
  src/app/serverlog-monitor/serverlog-monitor.component.spec.ts
  src/app/serverlog-monitor/serverlog-monitor.component.ts
  src/app/serverlog-monitor/serverlog-monitor.module.ts
  src/app/shared/shared.module.ts
  src/app/toast.service.ts
  src/app/toasts/toasts-container/toasts-container.component.html
  src/app/toasts/toasts-container/toasts-container.component.scss
  src/app/toasts/toasts-container/toasts-container.component.spec.ts
  src/app/toasts/toasts-container/toasts-container.component.ts
  src/app/toasts/toasts.module.ts
  src/app/topbar/topbar.component.html
  src/app/topbar/topbar.component.scss
  src/app/topbar/topbar.component.spec.ts
  src/app/topbar/topbar.component.ts
  src/app/topbar/topbar.module.ts
  src/app/topper/topper.component.html
  src/app/topper/topper.component.ts
  src/app/user/user.module.ts
  src/app/user/user.service.ts
  src/app/ws/web-socket.service.ts
  src/index.html
  src/styles.scss
Labels: feature
